In [1]:
import numpy as np
n1 = np.array([10 , 11 , 12 , 13 , 14])
n1


array([10, 11, 12, 13, 14])

In [3]:
n2 = np.array([[10,11,12],[13,14,15]])
n2


array([[10, 11, 12],
       [13, 14, 15]])

In [6]:
nzeors = np.zeros((1,4))
nzeors


array([[0., 0., 0., 0.]])

In [7]:
n3 = np.zeros((10,10))
n3

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [8]:
n4 = np.full((2,3),1)
n4

array([[1, 1, 1],
       [1, 1, 1]])

In [9]:
n1 = np.arange(10,20)
n1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [10]:
n2 = np.arange(10,50,5)
n2

array([10, 15, 20, 25, 30, 35, 40, 45])

In [14]:
n5 = np.random.randint(1,100,4)
n5

array([42, 19, 18, 54])

In [20]:
# /Checking the shape of an array and changing it
n6 = np.array([[1,2,3],[4,5,6]])
n6.shape
n6

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
n6.shape = (3,2)
n6.shape
n6

array([[1, 2],
       [3, 4],
       [5, 6]])

In [23]:
# Vstack , Hstack and Column_stack
n1 = np.array([1,2,3])
n2 = np.array([4,5,6])
np.vstack((n1,n2))


array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
np.hstack((n1,n2))

array([1, 2, 3, 4, 5, 6])

In [26]:
np.column_stack((n1,n2))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [30]:
#Intersect and Setdifference
n1 = np.array([1,2,3])
n2 = np.array([2,3,4])
np.intersect1d(n1,n2)


array([2, 3])

In [29]:
np.setdiff1d(n1,n2)

array([1])

In [34]:
# Addition of Numpy Array
n1 = np.array([1,2,3])
n2 = np.array([3,2,1])
np.sum([n1,n2])

12

In [35]:
# row wise addition
np.sum([n1,n2],axis = 1) 


array([6, 6])

In [36]:
# column wise addition
np.sum([n1,n2], axis = 0)

array([4, 4, 4])

In [40]:
# Numpy array Mathematics
# Addition
n1 = np.array([1,2,3])
n1 = n1+1
n1

array([2, 3, 4])

In [39]:
# substraction
n1 = n1- 2
n1

array([-1,  0,  1])

In [41]:
# Multiply and divide
n1 = n1 *2
n1

array([4, 6, 8])

In [42]:
n1 = n1 / 2
n1

array([2., 3., 4.])

In [43]:
# Numpy Math Functions
# Mean -> np.mean(array)
n1 = np.array([122,121,120])
np.mean(n1)

121.0

In [44]:
# Standard Deviation -> np.std(array)
np.std(n1)

0.816496580927726

In [45]:
# Median -> np.median(array)
np.median(n1)

121.0

In [46]:
# Save and Load numpy array
np.save('my_arr',n1)

In [48]:
np.load('my_arr.npy')

array([122, 121, 120])